### ISSUE TITLE
HpsJam now included in Jambox image for Raspberry Pi

### ISSUE THREAD

**Issue by kdoren** [hselasky/hpsjam#10] opened 2021-06-07 08:40 UTC
@hselasky  Hi Hans,
Thanks for your work!  I've included HpsJam in the latest Jambox image for Raspberry Pi, which might help it get more exposure.  Jambox is a pre-built SD-card image with multiple jamming apps.  It turns a Raspberry Pi into a complete ready-to-go jamming platform.  The apps are wrapped in startup scripts to make it really easy to run.  HpsJam client or server can be launched from desktop icons.  Check it out!  

https://github.com/kdoren/jambox-pi-gen

A few minor issues:
1.  both client and server throw an error message at startup:  "HpsJam: Cannot allocate UDP socket for payload: Address family not supported by protocol".  The message seems harmless (could it be ipv6 related?). Client and server both seem to work OK.
2.  the --ncpu command line argument is allowed by both client and server.  Is there any reason to use it for client?  If I set --ncpu 4 on client, additional processes are started, but they aren't stopped - closing the GUI in that case does not exit the HpsJam command.  Client seems to run OK with --ncpu 1.
3. The HpsJam client appears to run some kind of default server that allows the client to connect to itself on 127.0,0,1:22124.  The client process is listening to UDP port 22124 on 0.0.0.0, but does not respond to a connection attempt from another client, it only responds to itself on 127.0.0.1.   The odd result is that, if you try to run client and server on same machine, it works as expected if server starts first (127.0.0.1 will connect to server that allows connections from other clients).  But if client starts first, server start will throw the error"HpsJam: Cannot bind to IP port: Address already in use".

-Kevin

**Comment by hselasky** [comment] 2021-06-07 09:12
> @hselasky Hi Hans,
> Thanks for your work! I've included HpsJam in the latest Jambox image for Raspberry Pi, which might help it get more exposure. Jambox is a pre-built SD-card image with multiple jamming apps. It turns a Raspberry Pi into a complete ready-to-go jamming platform. The apps are wrapped in startup scripts to make it really easy to run. HpsJam client or server can be launched from desktop icons. Check it out!
> 

Hi Kevin,

Thank you for including HpsJAM in the Jambox image!

> https://github.com/kdoren/jambox-pi-gen
> 
> A few minor issues:
> 
>     1. both client and server throw an error message at startup:  "HpsJam: Cannot allocate UDP socket for payload: Address family not supported by protocol".  The message seems harmless (could it be ipv6 related?). Client and server both seem to work OK.

Yes, this seems to be related to IPv6, so if the jambox image doesn't have IPv6 support, then it will fail as expected.

>     2. the --ncpu command line argument is allowed by both client and server.  Is there any reason to use it for client?  If I set --ncpu 4 on client, additional processes are started, but they aren't stopped - closing the GUI in that case does not exit the HpsJam command.  Client seems to run OK with --ncpu 1.

The --ncpu command is only for the server side currently. If you set is non-zero for the client side some unused threads will be created simply.

>     3. The HpsJam client appears to run some kind of default server that allows the client to connect to itself on 127.0,0,1:22124.  The client process is listening to UDP port 22124 on 0.0.0.0, but does not respond to a connection attempt from another client, it only responds to itself on 127.0.0.1.   The odd result is that, if you try to run client and server on same machine, it works as expected if server starts first (127.0.0.1 will connect to server that allows connections from other clients).  But if client starts first, server start will throw the error"HpsJam: Cannot bind to IP port: Address already in use".

This is the expected behaviour. You can override the port numbers using the --port argument. Connecting two different clients back2back is not a supported feature. It only happens to work because the protocol is symmetric.

--HPS

**Comment by hselasky** [comment] 2021-06-20 15:34
Ping

**Comment by kdoren** [comment] 2021-06-23 00:30
Thanks, the current client startup script uses --ncpu 1 by default, which seems to work OK, but it will be removed in the next release.  I have ipv6 disabled so I guess the startup error messages are expected.

Thanks for clearing things up.

-Kevin

**Comment by hselasky** [comment] 2021-07-05 16:42
Closing this for now. JamBox is now listed under HpsJAM supported platforms.

**Closed by hselasky** 2021-07-05 16:42 UTC

**Comment by hselasky** [comment] 2021-07-18 11:06
There is a new version of HpsJam v1.0.15, please bump!

Thank you!

**Comment by kdoren** [comment] 2021-07-18 16:48
I put a build of v1.0.15 in my repo, so it's available via the "Update Apps" button.
I'll include it in the next jambox image release.

**Comment by hselasky** [comment] 2021-07-18 20:39
Thanks!
